"""
ACS Hardware-Aware Plan Schema Validator

Step 8 of the ACS project.

Validates a generated hardware-aware build plan against
hardware/schemas/plan.schema.json.
"""

from __future__ import annotations

import json
from pathlib import Path

from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[1]

PLAN_SCHEMA = ROOT / "hardware" / "schemas" / "plan.schema.json"


def load_json(path: Path) -> dict:
    """Load a JSON file."""

    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def validate_plan(plan: dict) -> list[str]:
    """
    Validate a hardware-aware plan against the Step 8 schema.

    Returns a list of validation error messages.
    """

    schema = load_json(PLAN_SCHEMA)

    validator = Draft202012Validator(schema)

    errors = sorted(
        validator.iter_errors(plan),
        key=lambda error: list(error.path),
    )

    return [
        error.message
        for error in errors
    ]


def main() -> None:
    """Validate an actual plan generated by the planning engine."""

    from planning_engine import build_hardware_plan

    plan = build_hardware_plan(
        controller="esp32_devkit",
        required_capabilities=[
            "stepper_rotation"
        ],
    )

    errors = validate_plan(plan)

    print("ACS Hardware-Aware Plan Schema Validator")
    print("=========================================")
    print()

    print("Test request:")
    print("Controller: esp32_devkit")
    print("Required capabilities: stepper_rotation")
    print()

    if errors:
        print("❌ Plan validation failed.")
        print()

        for error in errors:
            print(f"- {error}")

        raise SystemExit(1)

    print("Generated plan:")
    print()

    print(json.dumps(plan, indent=2))

    print()
    print("✅ Plan validation passed.")
    print(
        "The actual output of planning_engine.py "
        "conforms to plan.schema.json."
    )

if __name__ == "__main__":
    main()